apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-tapy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-tapy
    app.kubernetes.io/part-of: test-app-memk
  name: test-component-tapy
  namespace: build-e2e-hacbs-ziht
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-tapy
    weight: 100
status: {}
